services:
  web:
    build: .
    image: php-apache:latest
    container_name: php-apache
    restart: "always"
    depends_on:
      db:
        condition: service_healthy
    ports:
      - 8000:80
    networks:
      - php-apache
    volumes:
      - ./www:/var/www/html
    env_file:
      - .env

  db:
    image: mysql:8.0.28
    container_name: mysql
    restart: "always"
    ports:
      - 3306:3306
    networks:
      - php-apache
    volumes:
      - db_data:/var/lib/mysql
      - db_logs:/var/log/mysql
    environment:
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
      MYSQL_DATABASE: "${MYSQL_DATABASE}"
      MYSQL_USER: "${MYSQL_USER}"
      MYSQL_PASSWORD: "${MYSQL_PASSWORD}"
    healthcheck:
      test:
        [
          "CMD",
          "mysqladmin",
          "ping",
          "-p${MYSQL_ROOT_PASSWORD}"
        ]
      interval: 8s
      retries: 3
      timeout: 30s

volumes:
  db_data:
    driver: local
  db_logs:
    driver: local

networks:
  php-apache:
    driver: bridge
